#+TITLE: README
#+AUTHOR: Andrew Soutar
#+EMAIL: andrew@andrewsoutar.com
#+STARTUP: indent inlineimages latexpreview logdone constSI

* Tic Tac Toe
This is a simple tic-tac-toe game written in Java.
** How to build
First, download `utilities.jar', available from
https://github.com/andrewsoutarccm/utilities, and compile it according to its
instructions in a directory adjacent to the tictactoe directory. Make sure you
have a directory named `repo' as per the utilities build directions. Then, just
run `gradle build' in the tictactoe directory to build tictactoe.
** How to run
After you build, you can run tictactoe by typing `gradle run' in the main
directory. You will also find prepackaged distributions in the
build/distributions directory, jars in the build/libs directory, and class files
in the build/classes directory.
** How to edit
Simply clone and start editing. If you use eclipse or eclim, you can run `gradle
eclipse' in the main directory to generate the eclipse files, then simply import
the project into eclipse. Send me a pull request if you create anything
interesting.
